export const texts = {
  landing: {
    heroSubtitle: 'Portfolio fotografico.',
    albumsSectionHeading: 'Album',
  },
  album: {
    notFound: 'Album non trovato.',
    notFoundLink: 'Torna alla gallery',
    loading: 'Caricamento foto…',
    empty: 'Nessuna foto trovata in questo album.',
    error: {
      notFound: 'Album non trovato.',
      network: 'Errore di rete. Controlla la connessione.',
      unknown: 'Errore durante il caricamento. Riprova più tardi.',
      noImage: 'Le immagini non sono disponibili senza un URL pubblico R2.',
    },
  },
  about: {
    heading: 'Contatti',
    body: 'Scrivimi per informazioni su lavori e collaborazioni.',
    form: {
      namePlaceholder: 'Nome',
      emailPlaceholder: 'Email',
      subjectPlaceholder: 'Soggetto',
      messagePlaceholder: 'Messaggio',
      submitLabel: 'Invia',
      successMessage: 'Messaggio inviato. Ti risponderò presto.',
      challengeErrorMessage: 'Verifica anti-spam non riuscita. Ricarica la pagina e riprova.',
      errorMessage: "Errore durante l'invio. Riprova più tardi.",
    },
  },
  footer: {
    copyright: `© ${new Date().getFullYear()}`,
  },
  nav: {
    homeLabel: 'Portfolio',
    aboutLabel: 'Contatti',
  },
  admin: {
    site: {
      sectionTitle: 'Sito',
      nameLabel: 'Nome',
      bioLabel: 'Bio',
      instagramLabel: 'Instagram',
      save: 'Salva sito',
      saved: 'Sito salvato.',
      preview: 'Anteprima',
      previewClose: 'Chiudi',
      heroUpdated: 'Hero aggiornata.',
      heroReadError: 'Impossibile leggere le foto di questo album.',
      heroChooseAlbum: 'Scegli album…',
      heroNone: 'nessuna',
    },
    albums: {
      sectionTitle: 'Album',
      create: 'Nuovo album',
      exists: 'Esiste gia un album "{slug}".',
      titleInvalid: 'Titolo non valido.',
      titleReserved: '"{slug}" è un nome riservato.',
      delete: 'Elimina',
      deleteNameMismatch: 'Nome non corrispondente: cancellazione annullata.',
      deleteConfirmPrompt: 'Per eliminare scrivi il nome esatto dell\'album: "{titolo}"',
      loadError: 'Impossibile caricare gli album (rete o dati malformati).',
    },
    album: {
      save: 'Salva',
      saved: 'Album salvato.',
      cover: 'Cover',
      coverAsButton: 'Usa come cover',
      coverSelected: 'Cover selezionata: {nome} (premi Salva per confermare).',
      date: 'Data',
      sortedByDate: 'Foto ordinate per data.',
      confirmDeletePhoto: 'Eliminare {nome}?',
      deletePhoto: 'Elimina',
      manifestError: 'Impossibile caricare il manifest.',
      unsavedChanges: 'Ci sono modifiche non salvate. Uscire comunque?',
      uploadProgress: '{nome} — {fase}',
      uploadSuccess: 'Caricate {n} foto.',
      dropzoneConstraints: 'JPG, PNG, WebP fino a 20MB',
      unsupportedFormat: 'Non caricabili dal browser ({elenco}): HEIC e TIFF vanno convertiti prima, con `npm run compress`.',
      uploadPartial: 'Caricate {uploaded}, fallite {failed}: riprova trascinandole di nuovo.',
    },
    status: {
      lastAction: 'Ultima azione eseguita',
      error: 'Errore',
    },
    messages: {
      sectionTitle: 'Messaggi',
      empty: 'Nessun messaggio ricevuto.',
      loadError: 'Impossibile caricare i messaggi.',
      confirmDelete: 'Eliminare il messaggio di {nome}?',
      deleted: 'Messaggio eliminato.',
      reply: 'Rispondi',
      delete: 'Elimina',
    },
  },
};
